# Generated by Django 5.0.6 on 2024-07-07 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='images/')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='categories.category')),
            ],
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category1', to='categories.category')),
                ('secondCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category2', to='categories.category')),
            ],
            options={
                'indexes': [models.Index(fields=['firstCategory'], name='first_category_index'), models.Index(fields=['secondCategory'], name='second_category_index')],
            },
        ),
        migrations.AddConstraint(
            model_name='similarity',
            constraint=models.UniqueConstraint(fields=('firstCategory', 'secondCategory'), name='similarity_uniqueness'),
        ),
        migrations.AddConstraint(
            model_name='similarity',
            constraint=models.CheckConstraint(check=models.Q(('firstCategory_id__lt', models.F('secondCategory_id'))), name='firstCategory_id_lt_secondCategory_id'),
        ),
    ]
